### ISSUE TITLE
Unable to download aoi in test

### ISSUE THREAD

**Issue by lbross** [PSU-CSAR/django-ebagis#41]
Just tried to download 'north_aoi_1' from test and got the following stacktrace:
Traceback (most recent call last):
  File "c:\anaconda_x86\envs\ebagis_beta\lib\site-packages\celery\app\trace.py", line 240, in trace_task
    R = retval = fun(_args, *_kwargs)
  File "c:\anaconda_x86\envs\ebagis_beta\lib\site-packages\celery\app\trace.py", line 438, in **protected_call**
    return self.run(_args, *_kwargs)
  File "d:\projects\ebagis\testing\ebagis_beta\django-ebagis\ebagis\tasks.py", line 29, in export_data
    querydate=download.querydate
  File "d:\projects\ebagis\testing\ebagis_beta\django-ebagis\ebagis\models\aoi.py", line 246, in export
    self._zones.export(outpath, querydate=querydate)
  File "d:\projects\ebagis\testing\ebagis_beta\django-ebagis\ebagis\models\zones.py", line 171, in export
    hruzone.export(outpath, querydate)
  File "d:\projects\ebagis\testing\ebagis_beta\django-ebagis\ebagis\models\zones.py", line 135, in export
    latest.export(outpath, querydate)
  File "d:\projects\ebagis\testing\ebagis_beta\django-ebagis\ebagis\models\zones.py", line 98, in export
    self.paramgdb.export(output_dir, querydate)
AttributeError: 'NoneType' object has no attribute 'export'

**Comment by lbross** [comment]
I suspect this is related to the presence of a 'zones' folder. I was just able to download 'aoi1_05222013' but it doesn't have a zones folder.

**Comment by lbross** [comment]
AOI downloads do not include the 'maps' folder and it's contents. I confirmed that I did upload this folder as part of 'aoi1_05222013'. Per our [table](https://sites.google.com/site/nwccspatialservices/ebagis/database-design/ebagis-database-schema) of archived files, this should be included.

**Comment by jkeifer** [comment]
These bugs seem to be simple oversights on my part, and should be easily resolved. I will let you know once I have them fixed.

**Comment by jkeifer** [comment]
The first problem here was that north_aoi_1 had an HRU without a param.gdb. Apparently I made the param.gdb optional in the importer, but not in the exporter. Thus, the download failed because it tried to export a gdb that did not exist. I have tested downloading the aforementioned AOI and was successful.

I have corrected this problem, but I think the existence of this problem points to me needing to develop a more robust framework for handling object tasks. It would be great to develop a more declarative approach, one where properties like `optional = True` could be defined on a model and that would change the import/export behavior. At this point, however, the work required for such a change is prohibitive relative to the importance of addressing other outstanding issues and features. So I am simply leaving this note here for documentation and will take no further action.

The second issue of the maps not downloading turned out to be a number of bugs, but was mainly the fact that the maps were not even being imported. So no maps in the DB meant no maps in the download.

It turns out I never even implemented the map import function beyond a useless placeholder. So it was a complete miss on my end (none of my test AOIs had map docs, apparently). I fixed that function, which uncovered a few more bugs, squashed those, and now I believe all should be good on this front. I tested the upload with an AOI that had an arbitrary MXD in the maps folder, and that MXD was present in the download of that AOI.

Please retest the map downloading again, but be sure to re-upload your test AOI first.

As my tests passed, I am going to close this issue out with my commits, but feel free to reopen.

**Comment by lbross** [comment]
Still not seeing the maps folder and map_parameters.txt folder/file in my download. I uploaded 'aoi1_05222013_2' this afternoon to test this.

**Comment by jkeifer** [comment]
I believe this is now a matter of misunderstanding on my part. I expected only to find and/or care about .mxd files in the maps directory. I have never been aware of the map_parameters.txt file.

So now I know that file needs to be preserved. Are there any other files, besides .mxd files, that might be found in that directory and with which I should be concerned? Perhaps you can give me an example of the contents of an AOI's maps directory when it is loaded up with files.

Depending on the possible contents of the directory, it will likely take some significant rework to accommodate these changes, so I likely won't have this resolved immediately.

Also, is it currently a problem that the maps directory is not present if no contents are present? This is a limitation of zip files, as the directories are simply parts of the name of each compressed file. That is, the directories are only created if they have contents--you cannot zip an empty directory. If this is in fact a problem, this behavior will cease once I get the metadata worked out correctly: the maps directory should end up with a metadata file in it, and will then be included in the zip even if it is lacking other content.

**Comment by lbross** [comment]
I have been working with the mapping table on the bottom of [this page](https://sites.google.com/site/nwccspatialservices/ebagis/database-design/ebagis-database-schema) to determine what folders/files will be archived by eBagis. According to this table, in addition to the aforementioned files (*.mxd, map_parameters.txt) there may also be an analysis.xml file present. 

Geoffrey ... it would be good for you to review this table again too. The maps folder is used mostly by the original BAGIS so I am not entirely familiar with its potential contents.

It should not be a problem if the maps directory is not present if there are no contents. If BAGIS needs to add something here, it should be checking for the presence of the folder before trying to write any files.

**Comment by jkeifer** [comment]
In reviewing that table I see the files from this directory are listed as being archived if changed, e.g. version controlled. However, my recollection of the discussion surrounding these files was that we were not managing versions, changes would simply overwrite existing files.

@jdduh It would be good if you could also confirm the desired behavior for any files you want to be managed in the maps directory.

Also, I could possibly treat this folder a little more "dumbly" and simply grab anything in there, if that would be desired. I have been operating under the assumption that the files I'd find throughout the AOI structure would be well-prescribed and that I would know what to expect where, but if it turns out this folder is less rigid, then such an approach may be warranted.

**Comment by lbross** [comment]
I think we should treat this folder like the others. We should know what is in there and what we want to archive. If we allow anything to be uploaded the database could get a bunch of junk in it that we don't want. The users could do this either intentionally or unintentionally.

**Comment by jkeifer** [comment]
map_parameters.txt and analysis.xml in the maps folder need to be managed by ebagis, but versioning is not necessary.

**Comment by jkeifer** [comment]
I have created a new issue, #46 , for the map parameters and analysis files. The original issue has been resolved.
